name: Continuous Integration

on:
  push:
     

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301    
    - uses: actions/cache@v2
      id: nuget-packages
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
            ${{ runner.os }}-nuget-  
    - name: Install dependencies
      run: dotnet restore
    - name: Build VndbSharp
      run: dotnet pack VndbSharp/VndbSharp.csproj --configuration Release --no-restore    
    - name: Cli
      run: |
        dir ${{ github.workspace }}/VndbSharp/bin/Release/

  
